apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api-deployment
  labels:
    app: comments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments-api
  template:
    metadata:
      labels:
        app: comments-api
    spec:
      containers:
      - name: comments-api
        image: jromankiew/comments-api:latest
        ports:
        - containerPort: 8888
        env:
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_TABLE
          value: "comments"
        - name: DB_PASSWORD
          value: "postgres"
        - name: SSL_MODE
          value: "false" 
        - name: POSTGRES_PASSWD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: comments-api-service
spec:
  type: NodePort
  selector:
    app: comments-api
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30100
